const strings = [
    "Universal 1",
    "Universal 2",
    "Universal 3",
    "Universal 4",
    "Universal 5",
    "Universal 6",
    "Universal 7",
    "Universal 8",
    "Universal 9",
    "Self Defense 1",
    "Self Defense 2",
    "Self Defense 3",
    "Self Defense 4",
    "Self Defense 5",
    "Self Defense 6",
    "Self Defense 7",
    "Self Defense 8",
    "Self Defense 9",
    "Self Defense 10",
    "Self Defense 11",
    "Self Defense 12",
    "Self Defense 13",
    "Self Defense 14",
    "Self Defense 15",
    "Self Defense 16",
    "Self Defense 17",
    "Self Defense 18",
    "Self Defense 19",
    "Self Defense 20",
    "Self Defense 21",
    "Self Defense 22",
    "Self Defense 23",
    "Self Defense 24",
    "Self Defense 25",
    "Self Defense 26",
    "Self Defense 27",
    "Self Defense 28",
    "Star Form",
    "Intermediate Star Form",
    "Advanced Star Form",
    "Moon Form",
    "Enpi",
    "Bo Kata 1",
    "Kama Kata 1-3",
    "Sword 10 Moves",
    "Sword Form",
    "Elbows"
];
